### ISSUE TITLE
MDM Agent OOM

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1061]
We have multiple OOM on MDM agent:
```
Memory cgroup out of memory: Kill process 10008 (mdsd) score 1981 or sacrifice child
```

To check:
```
Events to search
   CustomerControlPlaneEvents
   CustomerSyslogEvents
Scoping conditions
   ResourceGroupName == mjudeikis
Filtering conditions
   PRIORITY equals any of 1,2,3,4
```

It is already running with:
```
         limits:
            cpu: 200m
            memory: 800Mi
          requests:
            cpu: 200m
            memory: 200Mi
```

Root cause might be that we send logs from all journald, and this causes service to overload. 

/cc @jim-minter @sozercan @charlesakalugwu we need to cut down of the logs we send or make MDM to have more resources :/
/kind bug
