### ISSUE TITLE
E2E test for ILB and ELB

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1111]
We had to make release to make sure ILB creation works: https://github.com/openshift/openshift-azure/commit/60bf54b7f7b1bbe7642fd7ebf4308804c5a6e8b1

We should test in E2E test if we can create services `type: LoadBalancer` with azure annotations:
```
apiVersion: v1
kind: Service
metadata:
  name: internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: internal
```
and alternative for ELB.
