### ISSUE TITLE
DNS and waagent race condition

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1164]
Master was not able to start due DNS and waagent race condition. All other masters started fine. Just one hanged: 

```
  dnsConfig:
    nameservers:
      - 168.63.129.16
    searches:
      - 
```
