### ISSUE TITLE
Resolve prometheus alerts firing on default install

### ISSUE THREAD

**Issue by jim-minter** [openshift/openshift-azure#1201]
```
{"Metric":"ALERTS","Dims":{"alertname":"DeadMansSwitch","alertstate":"firing","severity":"none"},"TS":"2019-02-27T02:00:12.496"}:1.000000|f
{"Metric":"ALERTS","Dims":{"alertname":"KubeControllerManagerDown","alertstate":"firing","severity":"critical"},"TS":"2019-02-27T02:00:12.496"}:1.000000|f
{"Metric":"ALERTS","Dims":{"alertname":"KubeSchedulerDown","alertstate":"firing","severity":"critical"},"TS":"2019-02-27T02:00:12.496"}:1.000000|f
{"Metric":"ALERTS","Dims":{"alertname":"TargetDown","alertstate":"firing","job":"kube-controllers","severity":"warning"},"TS":"2019-02-27T02:00:12.496"}:1.000000|f
```

**Comment by jim-minter** [comment]
@kwoodson ptal, fix, e2e test

**Comment by kwoodson** [comment]
> {"Metric":"ALERTS","Dims":{"alertname":"DeadMansSwitch","alertstate":"firing","severity":"none"},"TS":"2019-02-27T02:00:12.496"}:1.000000|f

This metric alerts by default to denote that the alert stack is functioning correctly.  https://github.com/coreos/prometheus-operator/issues/883

According to the above issue we can turn off which alerts we send based upon severity if this is something we want to do.

@jim-minter @mjudeikis @Makdaam 
thoughts?

**Comment by kwoodson** [comment]
> {"Metric":"ALERTS","Dims":{"alertname":"KubeControllerManagerDown","alertstate":"firing","severity":"critical"},"TS":"2019-02-27T02:00:12.496"}:1.000000|f

I believe what is occurring here is that the scrape to https://10.0.0.4:8444/metrics is failing because of the hostname.

Here is the configuration:
```
- job_name: openshift-monitoring/kube-controllers/0
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - api_server: null
    role: endpoints
    namespaces:
      names:
      - kube-system
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: false
```

An attempt to mimic this scrape with a curl inside of the prometheus pod:
```
sh-4.2$ curl -sS --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $KUBE_TOKEN" https://10.0.0.4:8444/metrics 
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.
```

A dump of the supported server names:
```
$ openssl s_client -showcerts -servername master-000000 -connect master-000000:8444 | openssl x509 -text
...
        Subject: CN=ktest.eastus.cloudapp.azure.com
...
            X509v3 Subject Alternative Name: 
                DNS:ktest.eastus.cloudapp.azure.com, DNS:master-000000, DNS:master-000001, DNS:master-000002, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:172.30.0.1
...
```

If I update the hostname to `master-000000` then the curl is successful. 
```
curl -sS --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $KUBE_TOKEN" https://master-000000:8444/metrics | head -n 10
# HELP ClusterRoleAggregator_adds Total number of adds handled by workqueue: ClusterRoleAggregator
# TYPE ClusterRoleAggregator_adds counter
ClusterRoleAggregator_adds 3476
# HELP ClusterRoleAggregator_depth Current depth of workqueue: ClusterRoleAggregator
# TYPE ClusterRoleAggregator_depth gauge
ClusterRoleAggregator_depth 0
...
```

Either we update the hosts in which we are scraping or we can turn off the verify option:
```
    insecure_skip_verify: false
```

Thoughts?
