### ISSUE TITLE
InvalidImageName when deploying applications

### ISSUE THREAD

**Issue by kwoodson** [openshift/openshift-azure#159]
When deploying a cluster I need to test whether the registry is working.  I deployed from /console the cakephp-mysql-persistent application.  It shows up as "InvalidImageName":
```
[root@master-000000 ~]# oc get pods
NAME                               READY     STATUS                  RESTARTS   AGE
cakephp-mysql-persistent-2-build   0/1       Init:InvalidImageName   0          57s
mysql-1-deploy                     0/1       InvalidImageName        0          5m
```

I checked the build pod and it has a broken image format:
```
[root@master-000000 ~]# oc get pods cakephp-mysql-persistent-2-build -o yaml | grep image
    image: 'docker.io/openshift/origin-:'
    imagePullPolicy: IfNotPresent
  imagePullSecrets:
    image: 'docker.io/openshift/origin-:'
    imagePullPolicy: IfNotPresent
    image: 'docker.io/openshift/origin-:'
    imagePullPolicy: IfNotPresent
  - image: 'docker.io/openshift/origin-:'
    imageID: ""
  - image: 'docker.io/openshift/origin-:'
    imageID: ""
        message: 'Failed to apply default image tag "docker.io/openshift/origin-:":
          couldn''t parse image reference "docker.io/openshift/origin-:": invalid
  - image: 'docker.io/openshift/origin-:'
    imageID: ""
```

I checked the master-config.yaml and the image string looks like this:
```
format: "docker.io/openshift/origin-:"
```

This leads me to believe that the string is not being handled correctly when it gets laid down.  This led me to this code:
https://github.com/openshift/openshift-azure/blob/master/pkg/arm/data/master-startup.sh#L171
https://github.com/openshift/openshift-azure/blob/master/pkg/config/generate.go#L46

I'll look for a few more minutes and will update.

@kargakis @jim-minter @mjudeikis, Any ideas on this one?
