### ISSUE TITLE
clusterrole.rbac.authorization.k8s.io "cluster-monitoring-view" not found

### ISSUE THREAD

**Issue by asalkeld** [openshift/openshift-azure#1667]
In pkg/sync/v6/data/ClusterRoleBinding.rbac.authorization.k8s.io/cluster-monitoring-view.yaml

```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
```
But there is no ClusterRole called "cluster-monitoring-view"

found when looking at some logs for https://github.com/openshift/openshift-azure/issues/1438
