### ISSUE TITLE
Group sync broken for Guest Accounts

### ISSUE THREAD

**Issue by mjudeikis** [openshift/openshift-azure#1766]
Group sync does now work for guest accounts:
Login flow user metadata:
```
[root@master-000000 ~]# oc get user
NAME                                       UID                                    FULL NAME            IDENTITIES
live.com#mjudeiki@redhat.com               b9a96ebd-9c03-11e9-bf3e-000d3a4f7cf4   mjudeiki             Azure AD:bC37ZKYYOzbjtsKrK6Cgazvzxczxczxc
mjudeikis@rhcuppettgmail.onmicrosoft.com   30aead80-9c03-11e9-8117-000d3a4f705b   Mangirdas Judeikis   Azure AD:RoejElH-phVpBcRWgh-zxc
```
Sync groups:
```
[root@master-000000 ~]# oc get groups
NAME                  USERS
osa-customer-admins   b-majude@microsoft.com, jaquincy@microsoft.com, mjudeiki@redhat.com, testuserdisabled@rhcuppettgmail.onmicrosoft.com
```
Config:
```
 - login: true                                                                                                                                                                                                                                                                                                                                                    
    mappingMethod: claim                                                                                                                                                                                                                                                                                                                                                   
    name: "Azure AD"                                                                                                                                                                                                                                                                                                                                                       
    provider:                                                                                                                                                                                                                                                                                                                                                              
      apiVersion: v1                                                                                                                                                                                                                                                                                                                                                       
      claims:                                                                                                                                                                                                                                                                                                                                                              
        email:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
        - email                                                                                                                                                                                                                                                                                                                                                            
        id:                                                                                                                                                                                                                                                                                                                                                                
        - sub                                                                                                                                                                                                                                                                                                                                                              
        name:                                                                                                                                                                                                                                                                                                                                                              
        - name                                                                                                                                                                                                                                                                                                                                                             
        preferredUsername:                                                                                                                                                                                                                                                                                                                                                 
        - unique_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
      clientID: "1c700e16-9002-4184-b178-xxxx"                                                                                                                                                                                                                                                                                                                     
      clientSecret:                                                                                                                                                                                                                                                                                                                                                        
        file: client.secret                                                                                                                                                                                                                                                                                                                                                
      kind: OpenIDIdentityProvider                                                                                                                                                                                                                                                                                                                                         
      urls:                                                                             
```

/cc @asalkeld, this is what I talked about.

**Comment by mjudeikis** [comment]
Guest user metedata contains `live.com#mjudeiki@redhat.com`

**Comment by mjudeikis** [comment]
```
[root@master-000000 ~]# oc get user
NAME                                       UID                                    FULL NAME            IDENTITIES
live.com#m.judeikis@gmail.com              f632dc90-9c06-11e9-bca3-000d3a4f7738   m.judeikis           Azure AD:oer7uzhLl7hN8Rh5vCdpF3zxxxxx
live.com#mjudeiki@redhat.com               b9a96ebd-9c03-11e9-bf3e-000d3a4f7cf4   mjudeiki             Azure AD:bC37ZKYYOzbjtsKrK6Cgab0xxxx
mjudeikis@rhcuppettgmail.onmicrosoft.com   30aead80-9c03-11e9-8117-000d3a4f705b   Mangirdas Judeikis   Azure AD:RoejElH-phVpBcRWgh-xxxx
````

**Comment by jim-minter** [comment]
@mjudeikis please can you explain clearly what the problem is, because it is currently unintelligible

**Comment by jim-minter** [comment]
relevant code snippet? https://github.com/openshift/openshift-azure/blob/master/pkg/controllers/customeradmin/group_mapping.go#L34-L40

**Comment by ehashman** [comment]
Maybe this is the issue? We're stripping the #EXT# thing from the email when we populate groups:

https://github.com/openshift/openshift-azure/blob/ace78496a704864f85949a67fc834c27d9561031/pkg/controllers/customeradmin/group_mapping.go#L34-L40

**Comment by asalkeld** [comment]
```
az ad user list | grep fooX
    "mail": "fooX@microsoft.com",
    "mailNickname": "fooX_microsoft.com#EXT#",
    "userPrincipalName": "fooX_microsoft.com#EXT#@rhcuppettgmail.onmicrosoft.com",
```
I think at the time kubernetes didn't allow the "#" in the object. This might be worth re-testing.

**Comment by mjudeikis** [comment]
Problem is that users who are synced via our process do not match user signing in data (data from the claim). And the data, we sync, has origin appended to the claim data. And this data does not exist in sync data. So in this case without hardcoding we can't easily fix sync process to append the data (below)

right'ish solution would somehow sync data without origin data. 

```
  {
    "accountEnabled": true,
    "ageGroup": null,
    "assignedLicenses": [],
    "assignedPlans": [],
    "city": null,
    "companyName": null,
    "consentProvidedForMinor": null,
    "country": null,
    "createdDateTime": "2018-10-04T13:41:56Z",
    "creationType": "Invitation",
    "deletionTimestamp": null,
    "department": null,
    "dirSyncEnabled": null,
    "displayName": "mjudeiki",
    "employeeId": null,
    "facsimileTelephoneNumber": null,
    "givenName": null,
    "immutableId": null,
    "isCompromised": null,
    "jobTitle": null,
    "lastDirSyncTime": null,
    "legalAgeGroupClassification": null,
    "mail": "foo@redhat.com",
    "mailNickname": "foo_redhat.com#EXT#",
    "mobile": null,
    "objectId": "35a61e42-516a-4543-803d-xxxxx",
    "objectType": "User",
    "odata.type": "Microsoft.DirectoryServices.User",
    "onPremisesDistinguishedName": null,
    "onPremisesSecurityIdentifier": null,
    "otherMails": [
      "mjudeiki@redhat.com"
    ],
    "passwordPolicies": null,
    "passwordProfile": null,
    "physicalDeliveryOfficeName": null,
    "postalCode": null,
    "preferredLanguage": null,
    "provisionedPlans": [],
    "provisioningErrors": [],
    "proxyAddresses": [
      "SMTP:foo@redhat.com"
    ],
    "refreshTokensValidFromDateTime": "2018-10-04T13:41:55Z",
    "showInAddressList": false,
    "signInNames": [],
    "sipProxyAddress": null,
    "state": null,
    "streetAddress": null,
    "surname": null,
    "telephoneNumber": null,
    "thumbnailPhoto@odata.mediaEditLink": "directoryObjects/35a61e42-516a-4543-803d-xxxx/Microsoft.DirectoryServices.User/thumbnailPhoto",
    "usageLocation": null,
    "userIdentities": [],
    "userPrincipalName": "fooi_redhat.com#EXT#@foo.onmicrosoft.com",
    "userState": "Accepted",
    "userStateChangedOn": "2019-06-27T17:42:46Z",
    "userType": "Guest"
  },
```

**Comment by mjudeikis** [comment]
MSFT suggested to use `oid` as claim object. It works, but it gives us these random symbols in UI. BUT mapping would be possible:
```
[mjudeiki@redhat openshift-azure]$ oc get identity
NAME                                                   IDP NAME   IDP USER NAME                                 USER NAME                              USER UID
Azure AD:35a61e42-516a-4543-803d-8cd639192a33          Azure AD   35a61e42-516a-4543-803d-8cd639192a33          35a61e42-516a-4543-803d-8cd639192a33   22488259-9ca1-11e9-8c4d-000d3a470264
Azure AD:qB7gCa118pTRwv8k61spUAIyOI8bibpRLrL0dyvbfkk   Azure AD   qB7gCa118pTRwv8k61spUAIyOI8bibpRLrL0dyvbfkk   b-fooo@microsoft.com                 0c6c6d08-9ca1-11e9-bedb-000d3a470359
```
we could sync using these:
```
[mjudeiki@redhat openshift-azure]$ oc get user
NAME                                   UID                                    FULL NAME                          IDENTITIES
35a61e42-516a-4543-803d-8cd639192a33   22488259-9ca1-11e9-8c4d-000d3a470264                                      Azure AD:35a61e42-516a-4543-803d-8cd639192a33
b-majude@microsoft.com                 0c6c6d08-9ca1-11e9-bedb-000d3a470359   Mangirdas Judeikis (Red Hat Inc)   Azure AD:qB7gCa118pTRwv8k61spUAIyOI8bibpRLrL0dyvbfkk
[mjudeiki@redhat openshift-azure]$ az ad user list | grep "35a61e42-516a-4543-803d-8cd639192a33"
    "objectId": "35a61e42-516a-4543-803d-8cd639192a33",
    "thumbnailPhoto@odata.mediaEditLink": "directoryObjects/35a61e42-516a-4543-803d-8cd639192a33/Microsoft.DirectoryServices.User/thumbnailPhoto",
```

**Comment by mjudeikis** [comment]
```
      claims:
        id:
        - sub
        preferredUsername:
        - oid
```

Works, but this would be a breaking change to the existing users.
