### ISSUE TITLE
remove hard coded location in storage class

### ISSUE THREAD

**Issue by pweil-** [openshift/openshift-azure#260]
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: azure
parameters:
  kind: managed
  location: eastus
  skuName: Premium_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: Immediate

```
